### PR TITLE
Fix #133, #139, and #180

### LINKED ISSUE #133: Allow imports in any order
Currently this is correct syntax:
```
import java.lang.Math.random
import protelis:state:time
```
while this is incorrect:
```
import protelis:state:time
import java.lang.Math.random
```
It seems there ought to be a way to allow imports to happen in any order, not only Java followed by Protelis.

### PR DESCRIPTION
**Pull request by DanySK**
This PR still needs better testing. This works:
```
// EXPECTED_RESULT: 2
import java.lang.Math.sqrt
def applier(fun){
	fun.apply(4)
}
applier(sqrt)
```
#133, #139, and #180 should be fixed already. We could merge this early and release a beta, or defer until appropriate testing is in place. Your call @jakebeal.

### CODE REVIEW

**Comment by jakebeal** [comment]
I see tests for avoiding wrappers and using static variables. Are there tests for enums and any-order imports yet? I didn't notice them, but might have missed it in the large diff.

**Comment by DanySK** [comment]
They are in the parser/linker 8.0.2

**Comment by jakebeal** [comment]
OK, I found them.  I approve.

**Comment by DanySK** [comment]
I'd like to cut a quick 11.1.0. Actually, if we stick to SemVer, we should release a 12.0, because I refactored an interface method to reflect the fact that it supports both Protelis functions and JVM static functions/fields.
How do you recommend to proceed?

**Comment by jakebeal** [comment]
Go for it with whichever feels best to you --- versioning doesn't really matter much to me, but if I were making the decision I'd probably call it 11.1, since the existence of 11.0 has been too short for anyone to build a dependence on this interface.

**Pull request merged**
