### PR TITLE
distanceBetweenWithMetric should use broadcast

### PR DESCRIPTION
**Pull request by jakebeal**

### CODE REVIEW

**Comment by w4bo** [comment]
@jakebeal 

[This](https://github.com/Protelis/Protelis/pull/99)  pull request fixes `distanceBetweenWithMetric`. In addition, it also introduces `countDevices`

**Comment by DanySK** [comment]
Hi @jakebeal,
I merged @w4bo's pull request. Please, update your pull request merging the current content of the develolp branch first.

**Comment by jakebeal** [comment]
This patch was constructed in the wrong workflow; I expect to pull the material out and make a different pull request now that I've got my workflow straightened out and am not developing on master.

**Comment by DanySK** [comment]
Perfect, I am closing this one then.

**Pull request closed without merging**
