### PR TITLE
Switch to the new HOFC semantics

### LINKED ISSUE #367: Protelis does not retain state for Java methods designed with alignment in mind
Consider this alternative, alignment-aware alternative implementation of `Tuple.map`:

```java
    @Override
    public Tuple map(final ExecutionContext ctx, final FunctionDefinition fun) {
        if (fun.getParameterCount() == 1 || fun.invokerShouldInitializeIt()) {
            return DatatypeFactory.createTuple(StreamUtils.zipWithIndex(
                Arrays.stream(arrayContents)
                    .map(it -> new Constant<>(JavaInteroperabilityUtils.METADATA, it)))
                    .map(elem -> {
                        final FunctionCall fc = new FunctionCall(JavaInteroperabilityUtils.METADATA, fun, ImmutableList.of(elem.getValue()));
                        ctx.newCallStackFrame((int) elem.getIndex());
                        fc.eval(ctx);
                        ctx.returnFromCallFrame();
                        return fc.getAnnotation();
                    })
                    .toArray()
            );
        }
        throw new IllegalArgumentException("Mapping function must take one parameter.");
    }
```

This causes this Protelis code:

```protelis
[0].map { rep(local <- it) { local + 1 } }
```

To return 1 at every round.

This is due to Protelis being based on the "superscripted" original semantics of the field calculus, hence creating a new FunctionCall resets the superscript status.

Ideally, we should modify the `ExecutionContext`, using for local state the same mechanics we use for shared state (namely, a `CodePath -> Object` mapping)

### PR DESCRIPTION
**Pull request by DanySK**
This PR introduces in Protelis an updated semantics of the higher order field calculus.
A Protelis program no longer have stored state, it is a pure function of its context.
This allowed for dropping the dreaded `copy()` methods meant to provide a way for creating new nodes of the AST without copying the saved state.

The current version of the PR passes the checks but has not yet been vetted for performance.
Some very obvious optimizations could be applied before merging. Nevertheless, I'd like to ask @jakebeal for a review before the performance tricks are applied.

On the user side: former valid Protelis code remains valid. Java methods calling Protelis might need to change. Alignment-aware Java methods can now retain state.
In particular, tuple methods `map`, `filter`, and `reduce` are now alignment and state aware, allowing for much cleaner Protelis tuple manipulation code -- also fixes #367

### CODE REVIEW

**Comment by DanySK** [comment]
image
Current performance in tests

**Comment by DanySK** [comment]
image
Results with `Invoke` optimization

**Comment by DanySK** [comment]
image

After function call site optimization, this is the performance.

**Comment by DanySK** [comment]
Optimization to `AlignedMap` led to further (marginal, few points percent) performance improvement for `multi*` and `timereplicated` users.

**Comment by DanySK** [comment]
@jakebeal PR ready.

**Comment by DanySK** [comment]
@jakebeal can you provide an approximate ETA for a review, or a comment? I'd like to merge this PR, it's blocking progress on some other activities relying on Protelis on my side. Thanks :pray:

**Comment by jakebeal** [comment]
Apologies - I've been getting so many notifications that didn't require my action, I missed that this one actually did.  Go for it.

**Comment by DanySK** [comment]
No problem @jakebeal, thanks :)

**Pull request merged**
