### PR TITLE
Added BIS gradient to coord:spreading

### PR DESCRIPTION
**Pull request by Harniver**

### CODE REVIEW

**Comment by w4bo** [comment]
The integration with test and library code is fine.

I would just suggest two tweaks:
- Code compliance: use `mux` as we do in the other gradients
- Performance: Minimize the number of `nbr`s (as they are computationally heavy)
```
public def bisGradientWithMetric(source, metric, radius, speed) {
    mux(source) { // this is compliant to the structure of other gradients
        0 
    } else {
        let loc = [Infinity, Infinity];
        rep (old <- loc) {
            let n = nbr(old); // we save 1 nbr
            let nx = n.get(0) + metric.apply();
            let nt = n.get(1) + self.nbrLag() + nbr(self.getDeltaTime());
            min(minHood([max(nx, nt*speed-radius), nt]), loc)
        }.get(0)
    } 
}
```
Or even
```
public def bisGradientWithMetric(source, metric, radius, speed) {
    mux(source) { // this is compliant to the structure of other gradients
        0 
    } else {
        let loc = [Infinity, Infinity];
        rep (old <- loc) {
            let n = nbr([old, self.getDeltaTime()]); // we save 2 nbr but we need to handle issue #127
            let nx = if(n.get(0)!=Infinity) {n.get(0).get(0)} else {Infinity} + metric.apply();
            let nt = if(n.get(0)!=Infinity) {n.get(0).get(1)} else {Infinity} + self.nbrLag() + n.get(1);
            min(minHood([max(nx, nt*speed-radius), nt]), loc)
        }.get(0)
    } 
}
```

**Comment by Harniver** [comment]
I find the second version aggregating `getDeltaTime` in the same `nbr` very ugly; but I can live with that if you decide for it and make it work. I am also quite surprised that there is a performance difference in doing an `nbr` of pairs and then "slice" the fields later... you know that better than me of course.

Regarding the `mux`, as you write it the code is wrong (it would produce `Infinity` in every device except the sources). If you want to use `mux`, it needs to be inside the `rep`. Please also notice that using always `Infinity` as starting value and selecting inside with a `mux` whether to snap it to zero, the calculation is delayed by one round (on the first round devices close to sources do not recognize it since their exported value is anyway `Infinity`).

**Comment by w4bo** [comment]
Yep. Sorry for being imprecise. I merely cut and pasted the code. Also, as you don't reduce `n`, but a tuple composed by `nx` and `nt`, `bisGradientWithMetric3` is not affected by issue 127. I tested the following 3 versions:
```
public def bisGradientWithMetric1(source, metric, radius, speed) { // add mux
    rep (old <- [Infinity, Infinity]) {
    	mux (source) { 
    		[0, 0]
    	} else {
    		let nx = nbr(old.get(0)) + metric.apply();
        	let nt = nbr(old.get(1)) + self.nbrLag() + nbr(self.getDeltaTime());
                // min(minHood([max(nx, nt*speed-radius), nt]), [Infinity, Infinity]) we don't need this now, right?
        	minHood([max(nx, nt*speed-radius), nt])
    	}
    }.get(0)
}
public def bisGradientWithMetric2(source, metric, radius, speed) { // save 1 nbr
    rep (old <- [Infinity, Infinity]) {
    	mux (source) { 
    		[0, 0]
    	} else {
    		let n = nbr(old);
    		let nx = n.get(0) + metric.apply();
        	let nt = n.get(1) + self.nbrLag() + nbr(self.getDeltaTime());
        	minHood([max(nx, nt*speed-radius), nt])
    	}
    }.get(0)
}
public def bisGradientWithMetric3(source, metric, radius, speed) {  // save 2 nbr
    rep (old <- [Infinity, Infinity]) {
    	mux (source) { 
    		[0, 0]
    	} else {
    		let n = nbr([old, self.getDeltaTime()]);
    		let nx = n.get(0).get(0) + metric.apply();
        	let nt = n.get(0).get(1) + self.nbrLag() + n.get(1);
        	minHood([max(nx, nt*speed-radius), nt])
    	}
    }.get(0)
}
```
Performance optimization is demanded to the implementation of the aggregate programming stack, of course. Still, slicing a field of tuples is a local computation, instead `nbr` might potentially involve complex (network) interactions. As such, I believe that, where possible (and considering a tradeof with code readability), we should minimize the interactions at library level. @DanySK and @jakebeal what do you think? Am I denaturing the algorithm?

**Comment by Harniver** [comment]
Your present proposals seem correct to me (even though they take 1 more round to react to input changes).

I have not enough details to judge precisely whether it is more efficient exporting two integers or a single pair of integers. I just know that in field computing exports are usually sent "all together" at the end of a computational round, and not asynchronously every time an `nbr` is called.
So it seems strange to me that an `nbr` is really triggering a network interaction. In fact, it seems more inefficient to build a field of tuples just to produce other fields, which could have been produced directly (that is why in my opinion using more `nbr`s would be more efficient).
Well, I made my point, now you decide what you like more!

**Comment by DanySK** [comment]
I myself am unsure whether a field of 2-ples is faster than two fields of numbers. I suspect @w4bo is marginally right on performance, though I believe that without any data to talk about this falls into the premature optimization category. Moreover, Protelis will necessarily undergo a very, very deep rework in the next future as it's got a number of issues that are hard to tackle - and no guarantee is provided on whether the performance will change. @Harniver is right about networking: any meaningful implementation of the network manager must send messages at the end of the round.
I'd recommend picking the version with the simplest, most straightforward algorithm, the one that "looks better".

**Pull request merged**
