### PR TITLE
protelis-lang

### PR DESCRIPTION
**Pull request by w4bo**
* `self.dt()` -> `self.getDeltaTime()`
* add new functions
    * `evaporation`
    * `countDevice` and `quorumSensing`
    * `publishSubscribe`
* add `nbrDelay` to `TimeAwareDevice`

### CODE REVIEW

**Comment by DanySK** [comment]
@w4bo, tests are failing here! What's happening?

**Comment by DanySK** [comment]
@w4bo, [the build currently fails](https://travis-ci.org/Protelis/Protelis/builds/185396844): can you fix this? I can't merge until there are failing tests.

**Comment by w4bo** [comment]
Build is now working

**Comment by DanySK** [comment]
I see we've got interface changes. This will require a new major release. Merging.

**Pull request merged**
