### PR TITLE
Fix for multiInstance over sharing

### PR DESCRIPTION
**Pull request by jschewebbn**
multiInstance needs to not extend outside of the list of
sources passed in.

@jakebeal  and I ran into a problem with multiInstance sharing information too far. This fixes the problem.

### CODE REVIEW

**Comment by DanySK** [comment]
Hi @jschewebbn 
the fix makes total sense to me. I'm awaiting the opinion of @jakebeal before merge.

@w4bo, you are the original author of multi instance, leave a comment if you feel like doing so.

**Comment by jakebeal** [comment]
@DanySK I jointly wrote this fix with @jschewebbn , so I approve as well.

**Comment by DanySK** [comment]
Let's release this

**Comment by DanySK** [comment]
ARGH, I didn't check the head branch and merged on master. Fixing now, sorry

**Pull request merged**
